Feat/captainfact auto contributions
dis-moi/backend pull request #327
Opened 2021-03-17 12:47 UTC by julienadamcom

Connection to the CaptainFact's GraphQL API to sync their DisMoi contributions and the youtube videos they analyse.

Usage: when a DisMoi user watches a video on youtube, if he follows the CaptainFact contributor and if the video has been analysed by the CaptainFact community, a bubble appears and allows to read the results of this analysis.

2021-03-19 12:46 UTC, julienadamcom commented
@lutangar @JalilArfaoui do we need to talk about it?

2021-03-19 13:26 UTC, lutangar commented
I'd love to review this if this can wait till monday :pray:

2021-03-22 11:07 UTC, lutangar requested changes
Overall I think the `execute` command logic should be splitted in smaller bites and I'd vote  against a new setting system right now.

Keep in mind these commands (bots, crawler, etc...) should be kept out of the system in the short (or mid?) terms. So some of my comments might not be super relevant as well.

2021-03-22 11:39 UTC, MaartenLMEM commented on src/Command/UpdateCaptainFactNoticesCommand.php
> +                    $message = 'Cette vidéo est en cours de fact-checking collaboratif sur CaptainFact ('.$commentsCount.' commentaire'.(($commentsCount) ? 's' : '').' au '.date('d/m/Y').'). <a href=
Yes, this template has been discussed with @julienadamcom 
And it may change in a few weeks after CaptainFact feedbacks one the whole engine.

2021-03-22 13:26 UTC, lutangar commented
Oh, another thing. Don't forget to run the `php-cs-fixer`. You may want to rebase on master to take advantage of the new pre-commit hook.

2021-03-22 16:49 UTC, julienadamcom commented on src/Command/UpdateCaptainFactNoticesCommand.php
> +    public static $settingKey = 'CF';
ok

2021-03-22 16:49 UTC, julienadamcom commented on src/Command/UpdateCaptainFactNoticesCommand.php
> + * TODO
no, I'll delete it

2021-03-22 16:52 UTC, julienadamcom commented on src/Command/UpdateCaptainFactNoticesCommand.php
> +            $response = $this->httpClient->request(
not sure we need to over-engineer this. This is only a small command that syncs data.

2021-03-22 16:55 UTC, julienadamcom commented on src/Command/UpdateCaptainFactNoticesCommand.php
> +                    ->createQuery("SELECT DISTINCT n.externalId FROM App\Entity\Notice n WHERE n.contributor=:contributor AND n.externalId LIKE :externalIdPattern")
Let's discuss it next time. I think we can't afford to have weeks of delays due to reviews for little outlying scripts like this...

2021-03-24 09:32 UTC, lutangar commented on src/Command/UpdateCaptainFactNoticesCommand.php
> +                    ->createQuery("SELECT DISTINCT n.externalId FROM App\Entity\Notice n WHERE n.contributor=:contributor AND n.externalId LIKE :externalIdPattern")
It think you're taking this the wrong way, I'm trying to give some general guidelines here. My comments are merely scratching the surface and it already seems too much to handle.

2021-03-24 09:37 UTC, lutangar commented on src/Command/UpdateCaptainFactNoticesCommand.php
> +            $response = $this->httpClient->request(
It's a matter of readability, other developers need to be able to, at least, read and understand your code. And smaller bites is the first to help here.
This is a very basic rule. I insist, we're still very, very, far away of over-engineering here.

2021-03-28 18:30 UTC, julienadamcom commented
Hi @lutangar, this is ready to be reviewed again

2021-03-29 12:06 UTC, lutangar requested changes
Nice rework overall :superhero: 
This is already far more readable and maintainable!
A few things left to fix and we should be good to go :+1:

2021-03-29 12:06 UTC, lutangar commented on translations/messages.fr.yml
> +  settings: Paramètres
These translations aren't used anymore.

2021-03-31 08:16 UTC, julienadamcom commented
@lutangar ping

2021-03-31 08:43 UTC, julienadamcom commented
Please allow me to merge this ugly code that will be kicked off as soon as the contribute API is available

2021-03-31 08:49 UTC, christpet commented
> Please allow me to merge this ugly code that will be kicked off as soon as the contribute API is available

Seems ok to me @lutangar for now, since we actually have a plan to deprecate this code. Thoughts?

2021-03-31 09:11 UTC, merged

2021-03-31 13:30 UTC, JalilArfaoui commented on src/Command/UpdateCaptainFactNoticesCommand.php
> +                    ->find('App\Entity\Setting', self::$settingKey)
I tend to agree @lutangar … In this case, we only needed one variable, a specific table and entity seems overkill to me …

I’m sorry I know this PR has been discussed / merged already, just giving my 2 cents here

2021-03-31 17:11 UTC, christpet commented
Merged! Only thing left to do is to deduplicate the database as you told me today, correct @julienadamcom ?

2021-04-13 17:30 UTC, MaartenLMEM commented
Since this issue works, we can assess it. 
It is really working as planned since today : April 13th is its starting day for audit (if Camille confirms there no other issue)

@zhinu Do y ou think it is fast for you to assess J+7 (April 13th > April 20th) days from those metrics : nb of views, %detail, %clics ? And compare it with two other big contributors : Le Même en Mieux and Info ou Intox ? 
Then, shall I add it to Analytics board ?